packages:
  - ./parsers/packages/*

catalog:
  '@sadan4/devtools-pretty-printer': 1.0.4
  '@types/node': ^25.6.0
  '@vitest/coverage-v8': ^4.1.4
  '@vitest/ui': ^4.1.4
  ts-api-utils: 2.5.0
  typescript: ^6.0.2
  vitest: ^4.1.4

patchedDependencies:
  '@types/ws@8.5.14': patches/@types__ws@8.5.14.patch
  ts-api-utils: patches/ts-api-utils.patch

verifyDepsBeforeRun: install
